import { Footer, Navbar } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import { StateContext } from "@/context/StateContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nik Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <StateContext>
          <div className="layout">
            <Toaster/>
            <header>
              <Navbar />
            </header>
            <main className="main-container">{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </StateContext>
      </body>
    </html>
  );
}
