import React from 'react'
import { Footer, Navbar } from '.'


export const metadata = {
  title: 'Nik Store',
  description: 'Generated by Nik store',
}

const Layout = () => {
  return (
    <div className='layout'>

    <header>
      <Navbar/>
    </header>
    <main className='main-container'>
    Empty
    </main>
    <footer>
      <Footer/>
    </footer>
    </div>
  )
}

export default Layout